[package]
name = "net-bridge-core"
version = "0.1.0"
edition = "2024"
license = "LGPL-3.0"

[dependencies]
# Runtime
tokio = { workspace = true }
tokio-util = { workspace = true }
futures-util = { workspace = true }

# Error handling
thiserror = { workspace = true }

# Transport
socket2 = { workspace = true }
quinn = { workspace = true }
quinn-plaintext = { workspace = true }
kcp-rs = { workspace = true }
fec = { workspace = true }
smux = { workspace = true }

# Record
dashmap = { workspace = true }
bytes = { workspace = true }
