/*
 * AUTO-GENERATED by `cargo xtask abi-header update`.
 * Source of truth: rust/crates/net-bridge-native/src/abi/.
 * DO NOT EDIT MANUALLY.
 */

#ifdef _WIN32
#define NB_EXPORT __declspec(dllexport)
#else
#define NB_EXPORT __attribute__((visibility("default")))
#endif
#define NB_API NB_EXPORT


#ifndef NETBRIDGE_H
#define NETBRIDGE_H

#include <stdint.h>
#include <stddef.h>

/*
 C ABI major version.
 */
#define NB_ABI_MAJOR 1

/*
 C ABI minor version.
 */
#define NB_ABI_MINOR 0

/*
 Supports the QUIC transport.
 */
#define NB_FEATURE_QUIC (1 << 0)

/*
 Supports the KCP transport.
 */
#define NB_FEATURE_KCP (1 << 1)

/*
 Emits `NB_EVENT_WRITABLE` when a connection can accept more data.
 */
#define NB_FEATURE_WRITABLE_EVENT (1 << 2)

/*
 Reports remote addresses as a fixed binary socket address struct.
 */
#define NB_FEATURE_BINARY_SOCKET_ADDRESS (1 << 3)

/*
 Emits `NB_EVENT_SERVER_STATE` for server lifecycle transitions.
 */
#define NB_FEATURE_SERVER_STATE_EVENT (1 << 4)

/*
 QUIC transport kind selector.
 */
#define NB_TRANSPORT_QUIC 1

/*
 KCP transport kind selector.
 */
#define NB_TRANSPORT_KCP 2

/*
 Connection is being established.
 */
#define NB_CONNECTION_CONNECTING 1

/*
 Connection is established and usable.
 */
#define NB_CONNECTION_CONNECTED 2

/*
 Connection reached a closed terminal state.
 */
#define NB_CONNECTION_CLOSED 3

/*
 Connection failed and reached a terminal state.
 */
#define NB_CONNECTION_FAILED 4

/*
 Connection state changed (`arg0`/`arg1` carry the state and reason).
 */
#define NB_EVENT_CONNECTION_STATE 1

/*
 Readable data arrived for an accepted/server connection (`object_id`).
 */
#define NB_EVENT_DATA_AVAILABLE 2

/*
 A previously blocked connection can accept more data.
 */
#define NB_EVENT_WRITABLE 3

/*
 A server accepted a new connection (`object_id` is the connection id).
 */
#define NB_EVENT_ACCEPTED 4

/*
 Server lifecycle state changed (`arg0` is a `NB_SERVER_STATE_*` value).
 */
#define NB_EVENT_SERVER_STATE 5

/*
 Server is running and accepting.
 */
#define NB_SERVER_STATE_RUNNING 1

/*
 Server stopped cleanly.
 */
#define NB_SERVER_STATE_STOPPED 2

/*
 Server failed and stopped.
 */
#define NB_SERVER_STATE_FAILED 3

/*
 Generic failure reason.
 */
#define NB_REASON_GENERIC 0

/*
 DNS resolution failed.
 */
#define NB_REASON_DNS 1

/*
 Local setup failed.
 */
#define NB_REASON_SETUP 2

/*
 The peer refused the connection.
 */
#define NB_REASON_REFUSED 3

/*
 The connection timed out.
 */
#define NB_REASON_TIMEOUT 4

/*
 A protocol error occurred.
 */
#define NB_REASON_PROTOCOL 5

/*
 The operation was cancelled.
 */
#define NB_REASON_CANCELLED 6

/*
 An internal error occurred.
 */
#define NB_REASON_INTERNAL 7

/*
 Minimum `struct_size` for `nb_context_options_v1_t`.
 */
#define NB_CONTEXT_OPTIONS_V1_MIN_SIZE 16

/*
 Minimum `struct_size` for `nb_callbacks_v1_t`.
 */
#define NB_CALLBACKS_V1_MIN_SIZE 16

/*
 Minimum `struct_size` for `nb_connect_options_v1_t`.
 */
#define NB_CONNECT_OPTIONS_V1_MIN_SIZE 40

/*
 Minimum `struct_size` for `nb_server_options_v1_t`.
 */
#define NB_SERVER_OPTIONS_V1_MIN_SIZE 48

/*
 Opaque native runtime context. Never dereferenced from C.
 */
typedef struct nb_context_t nb_context_t;

typedef int32_t nb_status_t;

/*
 Native context creation options.

 A zero value for `worker_threads` selects the runtime default.
 */
typedef struct {
  /*
   Size of the caller-provided struct in bytes.
   */
  uint32_t struct_size;
  /*
   Reserved for ABI growth; must be zero.
   */
  uint32_t flags;
  /*
   Worker thread count; 0 selects the runtime default.
   */
  uint32_t worker_threads;
  /*
   Reserved for ABI growth; must be zero.
   */
  uint32_t reserved0;
  /*
   Reserved for ABI growth; must be zero.
   */
  uint64_t reserved[4];
} nb_context_options_v1_t;

/*
 Event callback invoked on native worker threads.

 It must decode its primitive arguments and return quickly without blocking. NULL is not a valid
 `on_event`.
 */
typedef void (*nb_event_callback_v1)(uint32_t event_kind,
                                     uint64_t object_id,
                                     int64_t arg0,
                                     int64_t arg1);

/*
 Callbacks supplied to `context_create`.
 */
typedef struct {
  /*
   Size of the caller-provided struct in bytes.
   */
  uint32_t struct_size;
  /*
   Reserved for ABI growth; must be zero.
   */
  uint32_t reserved0;
  /*
   Required event callback; must not be NULL.
   */
  nb_event_callback_v1 on_event;
  /*
   Reserved for ABI growth; must be zero.
   */
  uint64_t reserved[4];
} nb_callbacks_v1_t;

/*
 Borrowed UTF-8 payload view. `data` is only valid for the duration of the downcall that produced it;
 `length == 0` with `data == NULL` is empty.
 */
typedef struct {
  /*
   Pointer to the payload bytes (may be NULL when `length == 0`).
   */
  const uint8_t *data;
  /*
   Number of valid bytes behind `data`.
   */
  uint32_t length;
  /*
   Reserved for ABI growth; must be zero.
   */
  uint32_t reserved0;
} nb_bytes_view_v1_t;

/*
 Outbound connection options for `connect`.
 */
typedef struct {
  /*
   Size of the caller-provided struct in bytes.
   */
  uint32_t struct_size;
  /*
   Transport selector: `NB_TRANSPORT_QUIC` or `NB_TRANSPORT_KCP`.
   */
  uint32_t transport_kind;
  /*
   UTF-8 host name (not NUL-terminated, call-scoped).
   */
  nb_bytes_view_v1_t host_utf8;
  /*
   Destination port in host byte order.
   */
  uint16_t port;
  /*
   Reserved for ABI growth; must be zero.
   */
  uint16_t reserved0;
  /*
   KCP profile selector (0/1 = balanced, 2 = aggressive).
   */
  uint32_t kcp_profile;
  /*
   Reserved for ABI growth; must be zero.
   */
  uint32_t flags;
  /*
   Reserved for ABI growth; must be zero.
   */
  uint64_t reserved[4];
} nb_connect_options_v1_t;

/*
 Fixed-width connection handle, scoped to the owning native context.
 */
typedef uint64_t nb_connection_t;

/*
 Fixed binary socket address.

 `family` is 4 (IPv4) or 6 (IPv6). `port` is in host byte order. For IPv4 the first 4 bytes of
 `address` hold the address and `scope_id` is always zero; for IPv6 all 16 bytes hold the address and
 `scope_id` carries the interface scope id.
 */
typedef struct {
  /*
   Address family: 4 or 6.
   */
  uint32_t family;
  /*
   Port in host byte order.
   */
  uint16_t port;
  /*
   Reserved for ABI growth; must be zero.
   */
  uint16_t reserved0;
  /*
   16-byte address storage (IPv4 uses the first 4 bytes).
   */
  uint8_t address[16];
  /*
   IPv6 scope id; always zero for IPv4.
   */
  uint32_t scope_id;
  /*
   Reserved for ABI growth; must be zero.
   */
  uint32_t reserved1;
} nb_socket_address_v1_t;

/*
 Server bind options for `server_start`.
 */
typedef struct {
  /*
   Size of the caller-provided struct in bytes.
   */
  uint32_t struct_size;
  /*
   Transport selector: `NB_TRANSPORT_QUIC` or `NB_TRANSPORT_KCP`.
   */
  uint32_t transport_kind;
  /*
   UTF-8 bind host; empty length selects the unspecified address.
   */
  nb_bytes_view_v1_t bind_host_utf8;
  /*
   Bind port in host byte order (0 selects an ephemeral port).
   */
  uint16_t port;
  /*
   Reserved for ABI growth; must be zero.
   */
  uint16_t reserved0;
  /*
   Maximum number of accepted connections.
   */
  uint32_t max_connections;
  /*
   KCP profile selector (0/1 = balanced, 2 = aggressive).
   */
  uint32_t kcp_profile;
  /*
   Reserved for ABI growth; must be zero.
   */
  uint32_t flags;
  /*
   Reserved for ABI growth; must be zero.
   */
  uint32_t reserved1;
  /*
   Reserved for ABI growth; must be zero.
   */
  uint64_t reserved[4];
} nb_server_options_v1_t;

/*
 Fixed-width server handle, scoped to the owning native context.
 */
typedef uint64_t nb_server_t;

/*
 Versioned function table returned by `netbridge_get_api`.

 The struct is append-only: new functions are only ever added to the trailing reserved area across
 minor revisions.
 */
typedef struct {
  /*
   ABI major version implemented by this table.
   */
  uint32_t abi_major;
  /*
   ABI minor version implemented by this table.
   */
  uint32_t abi_minor;
  /*
   Size of the full `NbApiV1` struct in bytes.
   */
  uint32_t struct_size;
  /*
   Reserved for ABI growth; must be zero.
   */
  uint32_t reserved0;
  /*
   Bit set of supported `NB_FEATURE_*` capabilities.
   */
  uint64_t feature_bits;
  /*
   Create a native runtime context.
   */
  nb_status_t (*context_create)(const nb_context_options_v1_t *options,
                                const nb_callbacks_v1_t *callbacks,
                                nb_context_t **out_context);
  /*
   Shut down a context, waiting up to `timeout_millis`.
   */
  nb_status_t (*context_shutdown)(nb_context_t *context,
                                  uint32_t timeout_millis);
  /*
   Destroy a shut-down context.
   */
  nb_status_t (*context_destroy)(nb_context_t *context);
  /*
   Open an outbound connection.
   */
  nb_status_t (*connect)(nb_context_t *context,
                         const nb_connect_options_v1_t *options,
                         nb_connection_t *out_connection);
  /*
   Query the state of a connection.
   */
  nb_status_t (*connection_state)(nb_context_t *context,
                                  nb_connection_t connection,
                                  uint32_t *out_state);
  /*
   Query the remote address of a connection.
   */
  nb_status_t (*connection_remote_address)(nb_context_t *context,
                                           nb_connection_t connection,
                                           nb_socket_address_v1_t *out_address);
  /*
   Write up to `length` bytes to a connection.
   */
  nb_status_t (*connection_write)(nb_context_t *context,
                                  nb_connection_t connection,
                                  const uint8_t *data,
                                  uint32_t length,
                                  uint32_t *out_written);
  /*
   Read up to `capacity` bytes from a connection.
   */
  nb_status_t (*connection_read)(nb_context_t *context,
                                 nb_connection_t connection,
                                 uint8_t *data,
                                 uint32_t capacity,
                                 uint32_t *out_read);
  /*
   Close a connection.
   */
  nb_status_t (*connection_close)(nb_context_t *context,
                                  nb_connection_t connection);
  /*
   Start a server and return its handle.
   */
  nb_status_t (*server_start)(nb_context_t *context,
                              const nb_server_options_v1_t *options,
                              nb_server_t *out_server);
  /*
   Query the bound port of a server.
   */
  nb_status_t (*server_port)(nb_context_t *context,
                             nb_server_t server,
                             uint16_t *out_port);
  /*
   Stop a server.
   */
  nb_status_t (*server_stop)(nb_context_t *context,
                             nb_server_t server);
  /*
   Reserved for ABI growth; must be zero.
   */
  uint64_t reserved[8];
} nb_api_v1_t;

#define NB_OK 0

#define NB_WOULD_BLOCK 1

#define NB_NOT_FOUND 2

#define NB_CLOSED 3

#define NB_INVALID_ARGUMENT 4

#define NB_INVALID_STATE 5

#define NB_ABI_MISMATCH 6

#define NB_NATIVE_UNAVAILABLE 7

#define NB_BIND_FAILED 8

#define NB_DNS_FAILED 9

#define NB_CONNECT_FAILED 10

#define NB_SHUTTING_DOWN 11

#define NB_TIMEOUT 12

#define NB_INTERNAL 13

#define NB_PANIC 14

#define NB_UNSUPPORTED 15

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Returns the net-bridge C ABI v1 function table.

 # Safety

 `out_api` must be NULL or point to writable, correctly aligned storage for
 a `*const nb_api_v1_t`. A NULL `out_api` yields `NB_INVALID_ARGUMENT`.
 */
NB_EXPORT
nb_status_t netbridge_get_api(uint32_t requested_major,
                              uint32_t minimum_minor,
                              const nb_api_v1_t **out_api);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* NETBRIDGE_H */
